# Generated by Django 4.2.9 on 2024-01-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
